interface cuisine{
    [key : string] : string
}
export const cuisines:cuisine = {
    "pizza": "Italian",
    "jalebi": "Indian",
    "pad thai": "Thai",
    "crepes": "French",
    "borscht": "Russian",
    "hummus": "Middle Eastern",
    "tamales": "Mexican",
    "ramen": "Japanese",
    "dolma": "Greek",
    "jerk chicken": "Jamaican",
    "fettuccine alfredo": "Italian",
    "peking duck": "Chinese",
    "pierogi": "Polish",
    "sauerbraten": "German",
    "fajitas": "Mexican",
    "souvlaki": "Greek",
    "chole bhature": "Indian",
    "laksa": "Malaysian",
    "tandoori chicken": "Indian",
    "gyoza": "Japanese",
    "arepas": "Venezuelan",
    "miso soup": "Japanese",
    "tortellini": "Italian",
    "clam chowder": "American",
    "bibimbap": "Korean",
    "nasi goreng": "Indonesian",
    "khachapuri": "Georgian",
    "mochi": "Japanese",
    "cannoli": "Italian",
    "kulfi": "Indian",
    "bratwurst": "German",
    "ceviche": "Peruvian",
    "shepherd’s pie": "British",
    "vindaloo": "Indian",
    "chimichanga": "Mexican-American",
    "roti canai": "Malaysian",
    "lamb tagine": "Moroccan",
    "cassoulet": "French",
    "schnitzel": "Austrian",
    "tteokbokki": "Korean",
    "pierna asada": "Latin American",
    "okonomiyaki": "Japanese",
    "escargot": "French",
    "bakso": "Indonesian",
    "irish stew": "Irish",
    "kimchi jjigae": "Korean",
    "kofta": "Middle Eastern",
    "pork adobo": "Filipino",
    "plov": "Central Asian",
    "gazpacho": "Spanish",
    "baba ganoush": "Middle Eastern",
    "tres leches cake": "Latin American",
    "stroopwafel": "Dutch",
    "tarte tatin": "French",
    "chimichurri": "Argentinian",
    "saag paneer": "Indian",
    "gado-gado": "Indonesian",
    "lassi": "Indian",
    "quesadilla": "Mexican"
  }
  